// Master mock dataset for KnowFlow AI client-side state and fallback

export const INITIAL_DOCUMENTS = [
  {
    id: "doc-001",
    filename: "Contract_001.pdf",
    file_type: "PDF",
    file_size: "342 KB",
    uploaded_at: "2026-03-28",
    status: "Completed",
    pages_count: 4,
    chunks_count: 18,
    entities_count: 8,
    relationships_count: 8,
    facts_count: 5,
    confidence_score: 0.96,
    needs_review_count: 2,
    summary: "Master hardware procurement contract between ABC Technologies Pvt. Ltd. and XYZ Corporation for 500 Dell PowerEdge servers worth ₹2.5 Crore.",
    text_content: "ABC Technologies Pvt. Ltd. entered into a supply agreement with XYZ Corporation for the purchase of 500 Dell PowerEdge servers worth INR 2.5 crore. The agreement was signed by John Smith on 15 March 2026 and is valid until 15 March 2028. Deliveries shall be executed in staggered batches at the Bangalore Technology Park facility. Standard enterprise SLA guarantee applies for 24 months from acceptance date.",
    pages: [
      {
        page_number: 1,
        title: "Master Service Agreement - Cover & Execution",
        text: "MASTER HARDWARE SUPPLY AGREEMENT (Ref: C001-2026)\n\nThis Master Supply Agreement is entered into on 15 March 2026 by and between:\n\n1. ABC Technologies Pvt. Ltd., an enterprise organized under the Companies Act with principal offices at Tech Park, Bangalore ('Purchaser'); and\n2. XYZ Corporation, an enterprise electronics manufacturer with regional operations in Mumbai ('Supplier').\n\nWHEREAS Purchaser desires to purchase data center computing hardware, and Supplier agrees to provide the specified units subject to the terms and stipulations herein."
      },
      {
        page_number: 2,
        title: "Scope of Supply & Commercial Consideration",
        text: "ABC Technologies Pvt. Ltd. entered into a supply agreement with XYZ Corporation for the purchase of 500 Dell PowerEdge servers worth INR 2.5 crore. The agreement was signed by John Smith on 15 March 2026 and is valid until 15 March 2028.\n\nSection 2.1 Hardware Specification:\nSupplier guarantees all Dell PowerEdge servers shall be configured with dual Intel Xeon processors, 256GB ECC DDR5 RAM, and redundant titanium power modules.\n\nSection 2.2 Payment Schedule:\nPayment shall be disbursed upon delivery milestones. Partial invoices may be submitted upon each batch dispatch."
      },
      {
        page_number: 3,
        title: "Delivery Terms & Logistics",
        text: "Section 3.1 Logistics Routing:\nAll shipments must be routed to ABC Technologies Data Center Unit II, Bangalore. Receiving inspection shall be performed within 5 business days of physical receipt.\n\nSection 3.2 Liquidated Damages:\nDelays exceeding 14 calendar days not attributable to force majeure shall incur penalties of 0.5% per week up to a ceiling of 5% of total contract value."
      },
      {
        page_number: 4,
        title: "Signatures & Execution Mandate",
        text: "IN WITNESS WHEREOF, the duly authorized representatives have executed this agreement as of the effective date.\n\nFor ABC Technologies Pvt. Ltd.:\nSigned: John Smith\nTitle: Authorised Signatory\nDate: 15 March 2026\n\nFor XYZ Corporation:\nSigned: Robert Vance\nTitle: Managing Director\nDate: 15 March 2026"
      }
    ]
  },
  {
    id: "doc-002",
    filename: "Invoice_034.pdf",
    file_type: "PDF",
    file_size: "184 KB",
    uploaded_at: "2026-03-29",
    status: "Completed",
    pages_count: 2,
    chunks_count: 8,
    entities_count: 7,
    relationships_count: 5,
    facts_count: 6,
    confidence_score: 0.98,
    needs_review_count: 0,
    summary: "Commercial tax invoice INV-2026-034 for batch 1 delivery of 200 Dell PowerEdge servers under Contract C001, total INR 1.0 Crore.",
    text_content: "Tax Invoice INV-2026-034 issued by XYZ Corporation to ABC Technologies Pvt. Ltd. for partial delivery of 200 Dell PowerEdge servers against Contract C001. Total amount payable: INR 1,00,00,000 (INR 1.0 Crore). Due date: 30 April 2026. Payment terms: Net 45 days. Billed to Bangalore HQ facility.",
    pages: [
      {
        page_number: 1,
        title: "Tax Invoice INV-2026-034",
        text: "TAX INVOICE # INV-2026-034\nDate of Issue: 20 March 2026\nDue Date: 30 April 2026 (Net 45 Days)\n\nISSUER:\nXYZ Corporation\nGSTIN: 27AAACX1234F1Z5\nMumbai Operations Center\n\nBILLED TO:\nABC Technologies Pvt. Ltd.\nTech Park, Bangalore\nGSTIN: 29AAACB9876E1Z2\n\nOrder Reference: Contract C001\nLine Item 1: Dell PowerEdge Rack Servers (Qty: 200)\nUnit Price: INR 50,000\nTotal Taxable Value: INR 1,00,00,000 (INR 1.0 Crore)\nIntegrated GST: Included\nTotal Payable: INR 1,00,00,000"
      },
      {
        page_number: 2,
        title: "Remittance Instructions & Banking",
        text: "Bank Remittance Details:\nBeneficiary: XYZ Corporation Commercial Escrow\nBank: HDFC Bank Corporate Branch Mumbai\nIFSC: HDFC0000123\nAccount: 50200019283741\nReference note must state INV-2026-034 / Contract C001."
      }
    ]
  },
  {
    id: "doc-003",
    filename: "Supplier_Agreement.pdf",
    file_type: "PDF",
    file_size: "512 KB",
    uploaded_at: "2026-03-25",
    status: "Completed",
    pages_count: 5,
    chunks_count: 22,
    entities_count: 9,
    relationships_count: 7,
    facts_count: 7,
    confidence_score: 0.94,
    needs_review_count: 1,
    summary: "Enterprise cloud infrastructure agreement between Apex Cloud Solutions and Global Logistics Corp for redundant rack clusters and Cisco Catalyst switches.",
    text_content: "Master Service & Hardware Supplier Agreement between Apex Cloud Solutions and Global Logistics Corp for redundant rack clusters and Cisco Catalyst switches. Total contract value INR 4.2 crore. Authorised signatory: Sarah Jenkins, VP Procurement. Effective date 01 January 2026.",
    pages: [
      {
        page_number: 1,
        title: "Service and Supply Agreement",
        text: "Master Service & Hardware Supplier Agreement between Apex Cloud Solutions and Global Logistics Corp for redundant rack clusters and Cisco Catalyst switches. Total contract value INR 4.2 crore. Authorised signatory: Sarah Jenkins, VP Procurement. Effective date 01 January 2026."
      }
    ]
  },
  {
    id: "doc-004",
    filename: "Annual_Report_2026.pdf",
    file_type: "PDF",
    file_size: "1.2 MB",
    uploaded_at: "2026-03-20",
    status: "Needs Review",
    pages_count: 12,
    chunks_count: 48,
    entities_count: 14,
    relationships_count: 11,
    facts_count: 15,
    confidence_score: 0.88,
    needs_review_count: 3,
    summary: "Annual fiscal overview containing disclosure of capital hardware expenditures and long-term commitments.",
    text_content: "Annual Fiscal Report 2026 - Capital Hardware Commitments Note 14.3: Infrastructure commitments include Master Supply Agreement Contract C001 entered with XYZ Corporation for server farm modernization, with an operational expiration recorded as June 2028.",
    pages: [
      {
        page_number: 7,
        title: "Note 14.3 - Infrastructure Commitments",
        text: "Annual Fiscal Report 2026 - Capital Hardware Commitments Note 14.3: Infrastructure commitments include Master Supply Agreement Contract C001 entered with XYZ Corporation for server farm modernization, with an operational expiration recorded as June 2028."
      }
    ]
  }
];

export const INITIAL_ENTITIES = [
  {
    id: "ent-001",
    name: "ABC Technologies Pvt. Ltd.",
    type: "Organization",
    mentions_count: 18,
    linked_entity_id: "ORG-1024",
    linked_entity_name: "ABC Technologies Group",
    confidence: 0.98,
    status: "Verified",
    source_doc_id: "doc-001",
    source_doc_name: "Contract_001.pdf",
    source_page: 2,
    evidence_text: "ABC Technologies Pvt. Ltd. entered into a supply agreement with XYZ Corporation...",
    properties: { Industry: "Information Technology", Country: "India", Registration: "CIN-U72200KA2015PTC" }
  },
  {
    id: "ent-002",
    name: "XYZ Corporation",
    type: "Organization",
    mentions_count: 12,
    linked_entity_id: "ORG-1028",
    linked_entity_name: "XYZ Corp Enterprise Electronics",
    confidence: 0.95,
    status: "Verified",
    source_doc_id: "doc-001",
    source_doc_name: "Contract_001.pdf",
    source_page: 2,
    evidence_text: "...supply agreement with XYZ Corporation for the purchase of 500 Dell PowerEdge servers...",
    properties: { Industry: "Hardware & Manufacturing", Region: "Asia Pacific", Vendor_Tier: "Tier 1" }
  },
  {
    id: "ent-003",
    name: "Dell PowerEdge servers",
    type: "Product",
    mentions_count: 14,
    linked_entity_id: "PROD-509",
    linked_entity_name: "Dell PowerEdge Enterprise Rack Server",
    confidence: 0.97,
    status: "Verified",
    source_doc_id: "doc-001",
    source_doc_name: "Contract_001.pdf",
    source_page: 2,
    evidence_text: "...for the purchase of 500 Dell PowerEdge servers worth INR 2.5 crore.",
    properties: { Category: "Data Center Compute", OEM: "Dell Technologies", Architecture: "x86_64 Dual Socket" }
  },
  {
    id: "ent-004",
    name: "John Smith",
    type: "Person",
    mentions_count: 4,
    linked_entity_id: null,
    linked_entity_name: null,
    confidence: 0.82,
    status: "Needs Review",
    source_doc_id: "doc-001",
    source_doc_name: "Contract_001.pdf",
    source_page: 2,
    evidence_text: "The agreement was signed by John Smith on 15 March 2026...",
    properties: { Role: "Authorised Signatory", Department: "Procurement / Operations" }
  },
  {
    id: "ent-005",
    name: "Contract C001",
    type: "Contract",
    mentions_count: 22,
    linked_entity_id: "CTR-9901",
    linked_entity_name: "Hardware Supply Agreement C001",
    confidence: 0.99,
    status: "Verified",
    source_doc_id: "doc-001",
    source_doc_name: "Contract_001.pdf",
    source_page: 1,
    evidence_text: "MASTER HARDWARE SUPPLY AGREEMENT (Ref: C001-2026)...",
    properties: { Term_Months: "24", Currency: "INR", Jurisdiction: "Bangalore" }
  },
  {
    id: "ent-006",
    name: "INR 2.5 crore",
    type: "Money",
    mentions_count: 6,
    linked_entity_id: "MON-25M",
    linked_entity_name: "₹25,000,000 INR",
    confidence: 0.99,
    status: "Verified",
    source_doc_id: "doc-001",
    source_doc_name: "Contract_001.pdf",
    source_page: 2,
    evidence_text: "...worth INR 2.5 crore.",
    properties: { NumericValue: 25000000, Currency: "INR" }
  },
  {
    id: "ent-007",
    name: "15 March 2026",
    type: "Date",
    mentions_count: 8,
    linked_entity_id: "DATE-20260315",
    linked_entity_name: "2026-03-15 ISO",
    confidence: 0.98,
    status: "Verified",
    source_doc_id: "doc-001",
    source_doc_name: "Contract_001.pdf",
    source_page: 2,
    evidence_text: "The agreement was signed by John Smith on 15 March 2026...",
    properties: { StandardDate: "2026-03-15" }
  },
  {
    id: "ent-008",
    name: "15 March 2028",
    type: "Date",
    mentions_count: 5,
    linked_entity_id: "DATE-20280315",
    linked_entity_name: "2028-03-15 ISO",
    confidence: 0.98,
    status: "Verified",
    source_doc_id: "doc-001",
    source_doc_name: "Contract_001.pdf",
    source_page: 2,
    evidence_text: "...and is valid until 15 March 2028.",
    properties: { StandardDate: "2028-03-15" }
  },
  {
    id: "ent-009",
    name: "Invoice INV-2026-034",
    type: "Invoice",
    mentions_count: 7,
    linked_entity_id: "INV-7034",
    linked_entity_name: "Tax Invoice 034",
    confidence: 0.99,
    status: "Verified",
    source_doc_id: "doc-002",
    source_doc_name: "Invoice_034.pdf",
    source_page: 1,
    evidence_text: "TAX INVOICE # INV-2026-034 Date of Issue: 20 March 2026",
    properties: { InvoiceNo: "INV-2026-034", Status: "Open" }
  },
  {
    id: "ent-010",
    name: "Bangalore Technology Park",
    type: "Location",
    mentions_count: 9,
    linked_entity_id: "LOC-BLR-01",
    linked_entity_name: "Bangalore Tech Park Facility",
    confidence: 0.96,
    status: "Verified",
    source_doc_id: "doc-001",
    source_doc_name: "Contract_001.pdf",
    source_page: 1,
    evidence_text: "...principal offices at Tech Park, Bangalore ('Purchaser')",
    properties: { City: "Bangalore", State: "Karnataka", Country: "India" }
  },
  {
    id: "ent-011",
    name: "INR 1.0 Crore",
    type: "Money",
    mentions_count: 4,
    linked_entity_id: "MON-10M",
    linked_entity_name: "₹10,000,000 INR",
    confidence: 0.99,
    status: "Verified",
    source_doc_id: "doc-002",
    source_doc_name: "Invoice_034.pdf",
    source_page: 1,
    evidence_text: "Total amount payable: INR 1,00,00,000 (INR 1.0 Crore).",
    properties: { NumericValue: 10000000, Currency: "INR" }
  },
  {
    id: "ent-012",
    name: "30 April 2026",
    type: "Date",
    mentions_count: 3,
    linked_entity_id: "DATE-20260430",
    linked_entity_name: "2026-04-30 ISO",
    confidence: 0.97,
    status: "Verified",
    source_doc_id: "doc-002",
    source_doc_name: "Invoice_034.pdf",
    source_page: 1,
    evidence_text: "Due date: 30 April 2026. Payment terms: Net 45 days.",
    properties: { StandardDate: "2026-04-30" }
  },
  {
    id: "ent-013",
    name: "Apex Cloud Solutions",
    type: "Organization",
    mentions_count: 11,
    linked_entity_id: "ORG-1040",
    linked_entity_name: "Apex Cloud Technologies Ltd.",
    confidence: 0.95,
    status: "Verified",
    source_doc_id: "doc-003",
    source_doc_name: "Supplier_Agreement.pdf",
    source_page: 1,
    evidence_text: "Master Service & Hardware Supplier Agreement between Apex Cloud Solutions...",
    properties: { Industry: "Cloud Infrastructure" }
  },
  {
    id: "ent-014",
    name: "Global Logistics Corp",
    type: "Organization",
    mentions_count: 8,
    linked_entity_id: "ORG-1055",
    linked_entity_name: "Global Logistics International",
    confidence: 0.94,
    status: "Verified",
    source_doc_id: "doc-003",
    source_doc_name: "Supplier_Agreement.pdf",
    source_page: 1,
    evidence_text: "...and Global Logistics Corp for redundant rack clusters...",
    properties: { Industry: "Logistics & Transport" }
  },
  {
    id: "ent-015",
    name: "Cisco Catalyst switches",
    type: "Product",
    mentions_count: 6,
    linked_entity_id: "PROD-612",
    linked_entity_name: "Cisco Catalyst 9000 Series Enterprise Switch",
    confidence: 0.96,
    status: "Verified",
    source_doc_id: "doc-003",
    source_doc_name: "Supplier_Agreement.pdf",
    source_page: 1,
    evidence_text: "...and Cisco Catalyst switches. Total contract value INR 4.2 crore.",
    properties: { Category: "Networking Infrastructure", OEM: "Cisco Systems" }
  },
  {
    id: "ent-016",
    name: "Sarah Jenkins",
    type: "Person",
    mentions_count: 5,
    linked_entity_id: "PER-441",
    linked_entity_name: "Sarah Jenkins (VP)",
    confidence: 0.93,
    status: "Verified",
    source_doc_id: "doc-003",
    source_doc_name: "Supplier_Agreement.pdf",
    source_page: 1,
    evidence_text: "Authorised signatory: Sarah Jenkins, VP Procurement.",
    properties: { Title: "VP Procurement", Employer: "Global Logistics Corp" }
  },
  {
    id: "ent-017",
    name: "Robert Vance",
    type: "Person",
    mentions_count: 3,
    linked_entity_id: "PER-502",
    linked_entity_name: "Robert Vance (MD)",
    confidence: 0.92,
    status: "Verified",
    source_doc_id: "doc-001",
    source_doc_name: "Contract_001.pdf",
    source_page: 4,
    evidence_text: "For XYZ Corporation: Signed: Robert Vance Title: Managing Director",
    properties: { Title: "Managing Director", Employer: "XYZ Corporation" }
  },
  {
    id: "ent-018",
    name: "Mumbai Operations Center",
    type: "Location",
    mentions_count: 4,
    linked_entity_id: "LOC-MUM-01",
    linked_entity_name: "XYZ Corp Mumbai Regional Center",
    confidence: 0.95,
    status: "Verified",
    source_doc_id: "doc-002",
    source_doc_name: "Invoice_034.pdf",
    source_page: 1,
    evidence_text: "XYZ Corporation GSTIN: 27AAACX1234F1Z5 Mumbai Operations Center",
    properties: { City: "Mumbai", State: "Maharashtra" }
  },
  {
    id: "ent-019",
    name: "June 2028",
    type: "Date",
    mentions_count: 2,
    linked_entity_id: null,
    linked_entity_name: null,
    confidence: 0.74,
    status: "Needs Review",
    source_doc_id: "doc-004",
    source_doc_name: "Annual_Report_2026.pdf",
    source_page: 7,
    evidence_text: "...with an operational expiration recorded as June 2028.",
    properties: { Note: "Contradicts Contract_001 expiry of 15 March 2028" }
  },
  {
    id: "ent-020",
    name: "INR 4.2 crore",
    type: "Money",
    mentions_count: 4,
    linked_entity_id: "MON-42M",
    linked_entity_name: "₹42,000,000 INR",
    confidence: 0.98,
    status: "Verified",
    source_doc_id: "doc-003",
    source_doc_name: "Supplier_Agreement.pdf",
    source_page: 1,
    evidence_text: "Total contract value INR 4.2 crore.",
    properties: { NumericValue: 42000000, Currency: "INR" }
  },
  {
    id: "ent-021",
    name: "01 January 2026",
    type: "Date",
    mentions_count: 4,
    linked_entity_id: "DATE-20260101",
    linked_entity_name: "2026-01-01 ISO",
    confidence: 0.98,
    status: "Verified",
    source_doc_id: "doc-003",
    source_doc_name: "Supplier_Agreement.pdf",
    source_page: 1,
    evidence_text: "Effective date 01 January 2026.",
    properties: { StandardDate: "2026-01-01" }
  }
];

export const INITIAL_RELATIONSHIPS = [
  {
    id: "rel-001",
    source_entity_id: "ent-001",
    source_entity_name: "ABC Technologies Pvt. Ltd.",
    target_entity_id: "ent-005",
    target_entity_name: "Contract C001",
    relation_type: "SIGNED",
    confidence: 0.98,
    status: "Supported",
    evidence_text: "ABC Technologies Pvt. Ltd. entered into a supply agreement with XYZ Corporation...",
    source_doc_id: "doc-001",
    source_doc_name: "Contract_001.pdf",
    source_page: 2,
    warning: null
  },
  {
    id: "rel-002",
    source_entity_id: "ent-002",
    source_entity_name: "XYZ Corporation",
    target_entity_id: "ent-003",
    target_entity_name: "Dell PowerEdge servers",
    relation_type: "SUPPLIES",
    confidence: 0.96,
    status: "Supported",
    evidence_text: "...supply agreement with XYZ Corporation for the purchase of 500 Dell PowerEdge servers...",
    source_doc_id: "doc-001",
    source_doc_name: "Contract_001.pdf",
    source_page: 2,
    warning: null
  },
  {
    id: "rel-003",
    source_entity_id: "ent-001",
    source_entity_name: "ABC Technologies Pvt. Ltd.",
    target_entity_id: "ent-003",
    target_entity_name: "Dell PowerEdge servers",
    relation_type: "PURCHASED",
    confidence: 0.96,
    status: "Supported",
    evidence_text: "ABC Technologies Pvt. Ltd. entered into a supply agreement with XYZ Corporation for the purchase of 500 Dell PowerEdge servers...",
    source_doc_id: "doc-001",
    source_doc_name: "Contract_001.pdf",
    source_page: 2,
    warning: null
  },
  {
    id: "rel-004",
    source_entity_id: "ent-004",
    source_entity_name: "John Smith",
    target_entity_id: "ent-005",
    target_entity_name: "Contract C001",
    relation_type: "SIGNED",
    confidence: 0.97,
    status: "Supported",
    evidence_text: "The agreement was signed by John Smith on 15 March 2026...",
    source_doc_id: "doc-001",
    source_doc_name: "Contract_001.pdf",
    source_page: 2,
    warning: null
  },
  {
    id: "rel-005",
    source_entity_id: "ent-005",
    source_entity_name: "Contract C001",
    target_entity_id: "ent-003",
    target_entity_name: "Dell PowerEdge servers",
    relation_type: "CONTAINS",
    confidence: 0.97,
    status: "Supported",
    evidence_text: "...for the purchase of 500 Dell PowerEdge servers worth INR 2.5 crore.",
    source_doc_id: "doc-001",
    source_doc_name: "Contract_001.pdf",
    source_page: 2,
    warning: null
  },
  {
    id: "rel-006",
    source_entity_id: "ent-005",
    source_entity_name: "Contract C001",
    target_entity_id: "ent-006",
    target_entity_name: "INR 2.5 crore",
    relation_type: "HAS_VALUE",
    confidence: 0.99,
    status: "Supported",
    evidence_text: "...worth INR 2.5 crore.",
    source_doc_id: "doc-001",
    source_doc_name: "Contract_001.pdf",
    source_page: 2,
    warning: null
  },
  {
    id: "rel-007",
    source_entity_id: "ent-005",
    source_entity_name: "Contract C001",
    target_entity_id: "ent-007",
    target_entity_name: "15 March 2026",
    relation_type: "STARTS_ON",
    confidence: 0.98,
    status: "Supported",
    evidence_text: "The agreement was signed by John Smith on 15 March 2026...",
    source_doc_id: "doc-001",
    source_doc_name: "Contract_001.pdf",
    source_page: 2,
    warning: null
  },
  {
    id: "rel-008",
    source_entity_id: "ent-005",
    source_entity_name: "Contract C001",
    target_entity_id: "ent-008",
    target_entity_name: "15 March 2028",
    relation_type: "EXPIRES_ON",
    confidence: 0.98,
    status: "Supported",
    evidence_text: "...and is valid until 15 March 2028.",
    source_doc_id: "doc-001",
    source_doc_name: "Contract_001.pdf",
    source_page: 2,
    warning: null
  },
  {
    id: "rel-009",
    source_entity_id: "ent-004",
    source_entity_name: "John Smith",
    target_entity_id: "ent-001",
    target_entity_name: "ABC Technologies Pvt. Ltd.",
    relation_type: "CEO_OF",
    confidence: 0.61,
    status: "Unsupported",
    evidence_text: "Signed: John Smith, Title: Authorised Signatory",
    source_doc_id: "doc-001",
    source_doc_name: "Contract_001.pdf",
    source_page: 4,
    warning: "No direct supporting evidence found. Document indicates 'Authorised Signatory', not Chief Executive Officer. System flagged to prevent hallucination."
  },
  {
    id: "rel-010",
    source_entity_id: "ent-009",
    source_entity_name: "Invoice INV-2026-034",
    target_entity_id: "ent-002",
    target_entity_name: "XYZ Corporation",
    relation_type: "ISSUED_BY",
    confidence: 0.99,
    status: "Supported",
    evidence_text: "Tax Invoice INV-2026-034 issued by XYZ Corporation...",
    source_doc_id: "doc-002",
    source_doc_name: "Invoice_034.pdf",
    source_page: 1,
    warning: null
  },
  {
    id: "rel-011",
    source_entity_id: "ent-009",
    source_entity_name: "Invoice INV-2026-034",
    target_entity_id: "ent-001",
    target_entity_name: "ABC Technologies Pvt. Ltd.",
    relation_type: "BILLED_TO",
    confidence: 0.99,
    status: "Supported",
    evidence_text: "...to ABC Technologies Pvt. Ltd. for partial delivery of 200 Dell PowerEdge servers...",
    source_doc_id: "doc-002",
    source_doc_name: "Invoice_034.pdf",
    source_page: 1,
    warning: null
  },
  {
    id: "rel-012",
    source_entity_id: "ent-009",
    source_entity_name: "Invoice INV-2026-034",
    target_entity_id: "ent-005",
    target_entity_name: "Contract C001",
    relation_type: "REFERENCES",
    confidence: 0.98,
    status: "Supported",
    evidence_text: "...against Contract C001.",
    source_doc_id: "doc-002",
    source_doc_name: "Invoice_034.pdf",
    source_page: 1,
    warning: null
  },
  {
    id: "rel-013",
    source_entity_id: "ent-013",
    source_entity_name: "Apex Cloud Solutions",
    target_entity_id: "ent-015",
    target_entity_name: "Cisco Catalyst switches",
    relation_type: "PURCHASED",
    confidence: 0.95,
    status: "Supported",
    evidence_text: "Master Service & Hardware Supplier Agreement between Apex Cloud Solutions and Global Logistics Corp for redundant rack clusters and Cisco Catalyst switches.",
    source_doc_id: "doc-003",
    source_doc_name: "Supplier_Agreement.pdf",
    source_page: 1,
    warning: null
  },
  {
    id: "rel-014",
    source_entity_id: "ent-016",
    source_entity_name: "Sarah Jenkins",
    target_entity_id: "ent-014",
    target_entity_name: "Global Logistics Corp",
    relation_type: "EMPLOYED_BY",
    confidence: 0.93,
    status: "Supported",
    evidence_text: "Authorised signatory: Sarah Jenkins, VP Procurement.",
    source_doc_id: "doc-003",
    source_doc_name: "Supplier_Agreement.pdf",
    source_page: 1,
    warning: null
  },
  {
    id: "rel-015",
    source_entity_id: "ent-017",
    source_entity_name: "Robert Vance",
    target_entity_id: "ent-002",
    target_entity_name: "XYZ Corporation",
    relation_type: "MANAGING_DIRECTOR_OF",
    confidence: 0.94,
    status: "Supported",
    evidence_text: "For XYZ Corporation: Signed: Robert Vance Title: Managing Director",
    source_doc_id: "doc-001",
    source_doc_name: "Contract_001.pdf",
    source_page: 4,
    warning: null
  },
  {
    id: "rel-016",
    source_entity_id: "ent-005",
    source_entity_name: "Contract C001",
    target_entity_id: "ent-019",
    target_entity_name: "June 2028",
    relation_type: "EXPIRES_ON",
    confidence: 0.72,
    status: "Disputed",
    evidence_text: "...with an operational expiration recorded as June 2028.",
    source_doc_id: "doc-004",
    source_doc_name: "Annual_Report_2026.pdf",
    source_page: 7,
    warning: "Contradiction detected: Expiration recorded as June 2028 in Annual Report vs 15 March 2028 in original Contract."
  }
];

export const INITIAL_FACTS = [
  {
    id: "fact-001",
    subject_id: "ent-005",
    subject_name: "Contract C001",
    predicate: "Contract Value",
    value: "₹2.5 Crore",
    confidence: 0.99,
    status: "Confirmed Fact",
    evidence_text: "The agreement ... worth INR 2.5 crore.",
    source_doc_id: "doc-001",
    source_doc_name: "Contract_001.pdf",
    source_page: 2
  },
  {
    id: "fact-002",
    subject_id: "ent-005",
    subject_name: "Contract C001",
    predicate: "Quantity",
    value: "500 Units",
    confidence: 0.97,
    status: "Confirmed Fact",
    evidence_text: "...for the purchase of 500 Dell PowerEdge servers worth INR 2.5 crore.",
    source_doc_id: "doc-001",
    source_doc_name: "Contract_001.pdf",
    source_page: 2
  },
  {
    id: "fact-003",
    subject_id: "ent-005",
    subject_name: "Contract C001",
    predicate: "Start Date",
    value: "15 Mar 2026",
    confidence: 0.98,
    status: "Confirmed Fact",
    evidence_text: "The agreement was signed by John Smith on 15 March 2026...",
    source_doc_id: "doc-001",
    source_doc_name: "Contract_001.pdf",
    source_page: 2
  },
  {
    id: "fact-004",
    subject_id: "ent-005",
    subject_name: "Contract C001",
    predicate: "Expiry Date",
    value: "15 Mar 2028",
    confidence: 0.98,
    status: "Confirmed Fact",
    evidence_text: "...and is valid until 15 March 2028.",
    source_doc_id: "doc-001",
    source_doc_name: "Contract_001.pdf",
    source_page: 2
  },
  {
    id: "fact-005",
    subject_id: "ent-005",
    subject_name: "Contract C001",
    predicate: "SLA Guarantee Period",
    value: "24 Months",
    confidence: 0.95,
    status: "Confirmed Fact",
    evidence_text: "Standard enterprise SLA guarantee applies for 24 months from acceptance date.",
    source_doc_id: "doc-001",
    source_doc_name: "Contract_001.pdf",
    source_page: 2
  },
  {
    id: "fact-006",
    subject_id: "ent-009",
    subject_name: "Invoice INV-2026-034",
    predicate: "Invoice Payable Amount",
    value: "₹1.0 Crore (INR 10,000,000)",
    confidence: 0.99,
    status: "Confirmed Fact",
    evidence_text: "Total amount payable: INR 1,00,00,000 (INR 1.0 Crore).",
    source_doc_id: "doc-002",
    source_doc_name: "Invoice_034.pdf",
    source_page: 1
  },
  {
    id: "fact-007",
    subject_id: "ent-009",
    subject_name: "Invoice INV-2026-034",
    predicate: "Units Delivered (Batch 1)",
    value: "200 Units",
    confidence: 0.98,
    status: "Confirmed Fact",
    evidence_text: "...for partial delivery of 200 Dell PowerEdge servers against Contract C001.",
    source_doc_id: "doc-002",
    source_doc_name: "Invoice_034.pdf",
    source_page: 1
  },
  {
    id: "fact-008",
    subject_id: "ent-009",
    subject_name: "Invoice INV-2026-034",
    predicate: "Payment Due Date",
    value: "30 April 2026",
    confidence: 0.97,
    status: "Confirmed Fact",
    evidence_text: "Due date: 30 April 2026. Payment terms: Net 45 days.",
    source_doc_id: "doc-002",
    source_doc_name: "Invoice_034.pdf",
    source_page: 1
  },
  {
    id: "fact-009",
    subject_id: "ent-009",
    subject_name: "Invoice INV-2026-034",
    predicate: "Payment Terms",
    value: "Net 45 Days",
    confidence: 0.99,
    status: "Confirmed Fact",
    evidence_text: "Payment terms: Net 45 days. Billed to Bangalore HQ facility.",
    source_doc_id: "doc-002",
    source_doc_name: "Invoice_034.pdf",
    source_page: 1
  },
  {
    id: "fact-010",
    subject_id: "ent-003",
    subject_name: "Dell PowerEdge servers",
    predicate: "Processor Architecture",
    value: "Dual Intel Xeon Scalable",
    confidence: 0.94,
    status: "Confirmed Fact",
    evidence_text: "Supplier guarantees all Dell PowerEdge servers shall be configured with dual Intel Xeon processors...",
    source_doc_id: "doc-001",
    source_doc_name: "Contract_001.pdf",
    source_page: 2
  },
  {
    id: "fact-011",
    subject_id: "ent-003",
    subject_name: "Dell PowerEdge servers",
    predicate: "RAM Specification",
    value: "256GB ECC DDR5",
    confidence: 0.95,
    status: "Confirmed Fact",
    evidence_text: "...256GB ECC DDR5 RAM, and redundant titanium power modules.",
    source_doc_id: "doc-001",
    source_doc_name: "Contract_001.pdf",
    source_page: 2
  },
  {
    id: "fact-012",
    subject_id: "ent-013",
    subject_name: "Apex Cloud Solutions",
    predicate: "Contract Value (Cloud Agreement)",
    value: "₹4.2 Crore",
    confidence: 0.98,
    status: "Confirmed Fact",
    evidence_text: "Total contract value INR 4.2 crore. Authorised signatory: Sarah Jenkins, VP Procurement.",
    source_doc_id: "doc-003",
    source_doc_name: "Supplier_Agreement.pdf",
    source_page: 1
  },
  {
    id: "fact-013",
    subject_id: "ent-013",
    subject_name: "Apex Cloud Solutions",
    predicate: "Agreement Effective Date",
    value: "01 January 2026",
    confidence: 0.98,
    status: "Confirmed Fact",
    evidence_text: "Effective date 01 January 2026.",
    source_doc_id: "doc-003",
    source_doc_name: "Supplier_Agreement.pdf",
    source_page: 1
  },
  {
    id: "fact-014",
    subject_id: "ent-001",
    subject_name: "ABC Technologies Pvt. Ltd.",
    predicate: "Primary Operations Center",
    value: "Bangalore Technology Park Facility",
    confidence: 0.96,
    status: "Confirmed Fact",
    evidence_text: "...principal offices at Tech Park, Bangalore ('Purchaser')",
    source_doc_id: "doc-001",
    source_doc_name: "Contract_001.pdf",
    source_page: 1
  },
  {
    id: "fact-015",
    subject_id: "ent-005",
    subject_name: "Contract C001",
    predicate: "Delivered Units to Date",
    value: "200 of 500 (40%)",
    confidence: 0.96,
    status: "Confirmed Fact",
    evidence_text: "Line Item 1: Dell PowerEdge Rack Servers (Qty: 200) against Contract C001",
    source_doc_id: "doc-002",
    source_doc_name: "Invoice_034.pdf",
    source_page: 1
  },
  {
    id: "fact-016",
    subject_id: "ent-005",
    subject_name: "Contract C001",
    predicate: "Outstanding Balance Remaining",
    value: "₹1.5 Crore",
    confidence: 0.93,
    status: "Possible",
    evidence_text: "Derived from ₹2.5 Cr total contract minus ₹1.0 Cr invoiced under INV-2026-034.",
    source_doc_id: "doc-002",
    source_doc_name: "Invoice_034.pdf",
    source_page: 1
  },
  {
    id: "fact-017",
    subject_id: "ent-005",
    subject_name: "Contract C001",
    predicate: "Expiry Date (Annual Report Claim)",
    value: "June 2028",
    confidence: 0.74,
    status: "Contradictory",
    evidence_text: "...with an operational expiration recorded as June 2028.",
    source_doc_id: "doc-004",
    source_doc_name: "Annual_Report_2026.pdf",
    source_page: 7
  },
  {
    id: "fact-018",
    subject_id: "ent-004",
    subject_name: "John Smith",
    predicate: "Corporate Position",
    value: "Chief Executive Officer (Unsubstantiated)",
    confidence: 0.61,
    status: "Unsupported",
    evidence_text: "Signed: John Smith, Title: Authorised Signatory",
    source_doc_id: "doc-001",
    source_doc_name: "Contract_001.pdf",
    source_page: 4
  },
  {
    id: "fact-019",
    subject_id: "ent-005",
    subject_name: "Contract C001",
    predicate: "Governing Jurisdiction",
    value: "High Court of Karnataka",
    confidence: 0.95,
    status: "Confirmed Fact",
    evidence_text: "...principal offices at Tech Park, Bangalore ('Purchaser'); governed under Karnataka jurisdiction.",
    source_doc_id: "doc-001",
    source_doc_name: "Contract_001.pdf",
    source_page: 1
  },
  {
    id: "fact-020",
    subject_id: "ent-014",
    subject_name: "Global Logistics Corp",
    predicate: "Procurement Representative",
    value: "Sarah Jenkins",
    confidence: 0.94,
    status: "Confirmed Fact",
    evidence_text: "Authorised signatory: Sarah Jenkins, VP Procurement.",
    source_doc_id: "doc-003",
    source_doc_name: "Supplier_Agreement.pdf",
    source_page: 1
  }
];

export const INITIAL_EVIDENCE = [
  {
    id: "evi-001",
    fact_id: "fact-001",
    relationship_id: "rel-006",
    text: "ABC Technologies Pvt. Ltd. entered into a supply agreement with XYZ Corporation for the purchase of 500 Dell PowerEdge servers worth INR 2.5 crore.",
    source_doc_id: "doc-001",
    source_doc_name: "Contract_001.pdf",
    source_page: 2,
    evidence_type: "Direct Statement",
    confidence: 0.99,
    status: "Supported",
    context_before: "This Master Supply Agreement is entered into on 15 March 2026...",
    context_after: "The agreement was signed by John Smith on 15 March 2026 and is valid until 15 March 2028."
  },
  {
    id: "evi-002",
    fact_id: "fact-002",
    relationship_id: "rel-005",
    text: "...for the purchase of 500 Dell PowerEdge servers worth INR 2.5 crore.",
    source_doc_id: "doc-001",
    source_doc_name: "Contract_001.pdf",
    source_page: 2,
    evidence_type: "Direct Statement",
    confidence: 0.97,
    status: "Supported",
    context_before: "ABC Technologies Pvt. Ltd. entered into a supply agreement with XYZ Corporation...",
    context_after: "The agreement was signed by John Smith on 15 March 2026..."
  },
  {
    id: "evi-003",
    fact_id: "fact-003",
    relationship_id: "rel-007",
    text: "The agreement was signed by John Smith on 15 March 2026 and is valid until 15 March 2028.",
    source_doc_id: "doc-001",
    source_doc_name: "Contract_001.pdf",
    source_page: 2,
    evidence_type: "Direct Statement",
    confidence: 0.98,
    status: "Supported",
    context_before: "...for the purchase of 500 Dell PowerEdge servers worth INR 2.5 crore.",
    context_after: "Deliveries shall be executed in staggered batches at the Bangalore facility."
  },
  {
    id: "evi-004",
    fact_id: "fact-004",
    relationship_id: "rel-008",
    text: "...and is valid until 15 March 2028.",
    source_doc_id: "doc-001",
    source_doc_name: "Contract_001.pdf",
    source_page: 2,
    evidence_type: "Direct Statement",
    confidence: 0.98,
    status: "Supported",
    context_before: "The agreement was signed by John Smith on 15 March 2026...",
    context_after: "Deliveries shall be executed in staggered batches."
  },
  {
    id: "evi-005",
    fact_id: "fact-006",
    relationship_id: "rel-010",
    text: "Total amount payable: INR 1,00,00,000 (INR 1.0 Crore). Due date: 30 April 2026.",
    source_doc_id: "doc-002",
    source_doc_name: "Invoice_034.pdf",
    source_page: 1,
    evidence_type: "Tabular Data",
    confidence: 0.99,
    status: "Supported",
    context_before: "Order Reference: Contract C001, Line Item 1: Dell PowerEdge Rack Servers (Qty: 200)",
    context_after: "Bank Remittance Details: Beneficiary: XYZ Corporation Commercial Escrow"
  },
  {
    id: "evi-006",
    fact_id: "fact-007",
    relationship_id: "rel-012",
    text: "...partial delivery of 200 Dell PowerEdge servers against Contract C001.",
    source_doc_id: "doc-002",
    source_doc_name: "Invoice_034.pdf",
    source_page: 1,
    evidence_type: "Direct Statement",
    confidence: 0.98,
    status: "Supported",
    context_before: "Tax Invoice INV-2026-034 issued by XYZ Corporation to ABC Technologies Pvt. Ltd.",
    context_after: "Total amount payable: INR 1,00,00,000 (INR 1.0 Crore)."
  },
  {
    id: "evi-007",
    fact_id: "fact-012",
    relationship_id: "rel-013",
    text: "Total contract value INR 4.2 crore. Authorised signatory: Sarah Jenkins, VP Procurement. Effective date 01 January 2026.",
    source_doc_id: "doc-003",
    source_doc_name: "Supplier_Agreement.pdf",
    source_page: 1,
    evidence_type: "Direct Statement",
    confidence: 0.98,
    status: "Supported",
    context_before: "Master Service & Hardware Supplier Agreement between Apex Cloud Solutions and Global Logistics Corp...",
    context_after: "Hardware clusters shall adhere to tier 4 specifications."
  },
  {
    id: "evi-008",
    fact_id: "fact-010",
    relationship_id: "rel-005",
    text: "Supplier guarantees all Dell PowerEdge servers shall be configured with dual Intel Xeon processors, 256GB ECC DDR5 RAM, and redundant titanium power modules.",
    source_doc_id: "doc-001",
    source_doc_name: "Contract_001.pdf",
    source_page: 2,
    evidence_type: "Direct Statement",
    confidence: 0.96,
    status: "Supported",
    context_before: "Section 2.1 Hardware Specification:",
    context_after: "Section 2.2 Payment Schedule: Payment shall be disbursed upon delivery milestones."
  },
  {
    id: "evi-009",
    fact_id: "fact-017",
    relationship_id: "rel-016",
    text: "...infrastructure commitments include Master Supply Agreement Contract C001 entered with XYZ Corporation for server farm modernization, with an operational expiration recorded as June 2028.",
    source_doc_id: "doc-004",
    source_doc_name: "Annual_Report_2026.pdf",
    source_page: 7,
    evidence_type: "Direct Statement",
    confidence: 0.74,
    status: "Disputed",
    context_before: "Annual Fiscal Report 2026 - Capital Hardware Commitments Note 14.3:",
    context_after: "Capital asset depreciation calculations proceed on straight line basis."
  },
  {
    id: "evi-010",
    fact_id: "fact-018",
    relationship_id: "rel-009",
    text: "Signed: John Smith, Title: Authorised Signatory, Date: 15 March 2026",
    source_doc_id: "doc-001",
    source_doc_name: "Contract_001.pdf",
    source_page: 4,
    evidence_type: "Inferred",
    confidence: 0.61,
    status: "In Review",
    context_before: "For ABC Technologies Pvt. Ltd.:",
    context_after: "For XYZ Corporation: Signed: Robert Vance Title: Managing Director"
  }
];

export const INITIAL_REVIEW_ITEMS = [
  {
    id: "rev-001",
    category: "Unmatched",
    title: "Unmatched Entity: ABC Technologies",
    extracted_text: "ABC Technologies",
    possible_match: "ABC Technologies Pvt. Ltd.",
    match_id: "ORG-1024",
    similarity: 0.96,
    confidence: 0.88,
    warning: "Extracted string 'ABC Technologies' matches registered enterprise 'ABC Technologies Pvt. Ltd.' with 96% token similarity. Awaiting human confirmation to link.",
    evidence: "ABC Technologies entered into a supply agreement with XYZ Corporation...",
    source_doc: "Contract_001.pdf",
    source_page: 2,
    status: "Pending"
  },
  {
    id: "rev-002",
    category: "Low Confidence",
    title: "Low Confidence Relationship: John Smith → CEO_OF → ABC Technologies",
    extracted_text: "John Smith → CEO_OF → ABC Technologies",
    possible_match: null,
    match_id: null,
    similarity: null,
    confidence: 0.61,
    warning: "No direct supporting evidence found. Document only designates 'Authorised Signatory', not Chief Executive Officer. System flagged to prevent hallucination.",
    evidence: "Signed: John Smith, Title: Authorised Signatory, Date: 15 March 2026",
    source_doc: "Contract_001.pdf",
    source_page: 4,
    status: "Pending"
  },
  {
    id: "rev-003",
    category: "Contradiction",
    title: "Contradictory Fact: Contract C001 Expiry Date",
    extracted_text: "Expiry Date: 15 March 2028 vs June 2028",
    possible_match: null,
    match_id: null,
    similarity: null,
    confidence: 0.74,
    warning: "Contract_001.pdf states expiry is 15 March 2028; Annual_Report_2026.pdf Note 14.3 states June 2028. System preserves both citations pending human adjudication.",
    evidence: "Contract_001.pdf (Page 2): '...valid until 15 March 2028' | Annual_Report_2026.pdf (Page 7): '...operational expiration recorded as June 2028.'",
    source_doc: "Contract_001.pdf & Annual_Report_2026.pdf",
    source_page: 2,
    status: "Pending"
  },
  {
    id: "rev-004",
    category: "Ambiguous Relationship",
    title: "Ambiguous Relationship: XYZ Corporation → OWNS vs SUPPLIES → Dell Servers",
    extracted_text: "XYZ Corporation → [RELATION] → Dell PowerEdge servers",
    possible_match: "XYZ Corporation SUPPLIES Dell PowerEdge servers",
    match_id: "REL-SUPPLY",
    similarity: 0.85,
    confidence: 0.78,
    warning: "Initial semantic parser proposed OEM ownership; ontology confirms XYZ Corporation is a certified value-added supplier, not original manufacturer (Dell Technologies).",
    evidence: "...supply agreement with XYZ Corporation for the purchase of 500 Dell PowerEdge servers...",
    source_doc: "Contract_001.pdf",
    source_page: 2,
    status: "Pending"
  },
  {
    id: "rev-005",
    category: "Unmatched",
    title: "Unmatched Entity: Bangalore HQ Facility",
    extracted_text: "Bangalore HQ facility",
    possible_match: "Bangalore Technology Park Facility",
    match_id: "LOC-BLR-01",
    similarity: 0.89,
    confidence: 0.84,
    warning: "Invoice designates delivery to 'Bangalore HQ facility'. Semantic model has 'Bangalore Technology Park Facility' (LOC-BLR-01). Link suggested.",
    evidence: "Payment terms: Net 45 days. Billed to Bangalore HQ facility.",
    source_doc: "Invoice_034.pdf",
    source_page: 1,
    status: "Pending"
  }
];

export const INITIAL_CONTRADICTIONS = [
  {
    id: "contra-001",
    title: "Contract C001 Expiry Date Mismatch",
    subject: "Contract C001",
    property_name: "Expiry Date",
    doc_a_id: "doc-001",
    doc_a_name: "Contract_001.pdf (Original Executed Agreement)",
    doc_a_value: "15 March 2028",
    doc_a_evidence: "The agreement was signed by John Smith on 15 March 2026 and is valid until 15 March 2028.",
    doc_b_id: "doc-004",
    doc_b_name: "Annual_Report_2026.pdf (Fiscal Report Note 14.3)",
    doc_b_value: "June 2028",
    doc_b_evidence: "...with an operational expiration recorded as June 2028.",
    status: "Needs Human Review",
    resolution_note: null
  },
  {
    id: "contra-002",
    title: "Dell Server Processor Tier Discrepancy",
    subject: "Dell PowerEdge Servers",
    property_name: "Processor Generation",
    doc_a_id: "doc-001",
    doc_a_name: "Contract_001.pdf",
    doc_a_value: "Dual Intel Xeon Scalable DDR5",
    doc_a_evidence: "Supplier guarantees all Dell PowerEdge servers shall be configured with dual Intel Xeon processors, 256GB ECC DDR5 RAM...",
    doc_b_id: "doc-003",
    doc_b_name: "Supplier_Agreement.pdf",
    doc_b_value: "AMD EPYC 9004 Architecture",
    doc_b_evidence: "Alternate compute racks specified under Annexure B quote AMD EPYC 9004 clusters.",
    status: "Needs Human Review",
    resolution_note: null
  }
];

export const SEMANTIC_MODEL_DATA = [
  {
    id: "sem-org",
    name: "Organization",
    color: "#3b82f6",
    description: "Legally incorporated company, business enterprise, or institutional supplier.",
    properties: ["legal_name", "tax_identifier", "registration_country", "industry", "headquarters_city"],
    allowed_relationships: [
      { target: "Contract", relation: "signs" },
      { target: "Product", relation: "purchases" },
      { target: "Product", relation: "supplies" },
      { target: "Invoice", relation: "issues" },
      { target: "Invoice", relation: "pays" }
    ],
    examples: ["ABC Technologies Pvt. Ltd.", "XYZ Corporation", "Apex Cloud Solutions"],
    instances_count: 48
  },
  {
    id: "sem-per",
    name: "Person",
    color: "#8b5cf6",
    description: "Individual human actor such as an executive, authorized signatory, or account manager.",
    properties: ["full_name", "job_title", "department", "email", "authorization_level"],
    allowed_relationships: [
      { target: "Contract", relation: "signs" },
      { target: "Organization", relation: "employed_by" },
      { target: "Organization", relation: "executes_for" }
    ],
    examples: ["John Smith", "Robert Vance", "Sarah Jenkins"],
    instances_count: 28
  },
  {
    id: "sem-prod",
    name: "Product",
    color: "#10b981",
    description: "Physical hardware unit, software license, or subscription deliverable.",
    properties: ["sku", "oem_manufacturer", "category", "unit_metric", "hardware_specifications"],
    allowed_relationships: [
      { target: "Contract", relation: "specified_in" },
      { target: "Invoice", relation: "billed_in" }
    ],
    examples: ["Dell PowerEdge servers", "Cisco Catalyst switches", "Titanium Rack Clusters"],
    instances_count: 34
  },
  {
    id: "sem-ctr",
    name: "Contract",
    color: "#f59e0b",
    description: "Legally binding agreement, master service agreement, or procurement contract.",
    properties: ["contract_reference", "title", "governing_jurisdiction", "term_months", "sla_guarantee"],
    allowed_relationships: [
      { target: "Product", relation: "contains" },
      { target: "Money", relation: "has_value" },
      { target: "Date", relation: "starts_on" },
      { target: "Date", relation: "expires_on" }
    ],
    examples: ["Contract C001", "Hardware Supply Agreement C001-2026", "Cloud Agreement 2026"],
    instances_count: 16
  },
  {
    id: "sem-inv",
    name: "Invoice",
    color: "#06b6d4",
    description: "Financial billing document specifying payment liabilities and delivery batches.",
    properties: ["invoice_number", "payment_terms", "gstin_tax_code", "bank_account", "due_date"],
    allowed_relationships: [
      { target: "Organization", relation: "issued_by" },
      { target: "Organization", relation: "billed_to" },
      { target: "Contract", relation: "references" },
      { target: "Money", relation: "total_due" }
    ],
    examples: ["Invoice INV-2026-034", "Billing Schedule B-101"],
    instances_count: 22
  },
  {
    id: "sem-loc",
    name: "Location",
    color: "#ec4899",
    description: "Physical facility, data center campus, city, or delivery destination.",
    properties: ["facility_name", "city", "state_province", "country", "postal_code"],
    allowed_relationships: [
      { target: "Organization", relation: "headquarters_of" },
      { target: "Contract", relation: "delivery_point_for" }
    ],
    examples: ["Bangalore Technology Park", "Mumbai Operations Center"],
    instances_count: 19
  },
  {
    id: "sem-date",
    name: "Date",
    color: "#64748b",
    description: "Temporal point defining execution, effective term, milestone, or expiry.",
    properties: ["iso_string", "calendar_year", "calendar_quarter"],
    allowed_relationships: [
      { target: "Contract", relation: "effective_milestone_for" }
    ],
    examples: ["15 March 2026", "15 March 2028", "30 April 2026"],
    instances_count: 52
  },
  {
    id: "sem-mon",
    name: "Money",
    color: "#14b8a6",
    description: "Financial consideration, transaction price, contract value, or currency denomination.",
    properties: ["amount_numeric", "currency_code", "formatted_display"],
    allowed_relationships: [
      { target: "Contract", relation: "commercial_value_of" },
      { target: "Invoice", relation: "receivable_balance_of" }
    ],
    examples: ["INR 2.5 crore", "INR 1.0 Crore", "INR 4.2 crore"],
    instances_count: 31
  }
];

export const INITIAL_ANALYTICS = {
  kpis: {
    documents_processed: 128,
    documents_processed_today: 12,
    entities_extracted: 2481,
    entities_today: 86,
    relationships_discovered: 4820,
    relationships_today: 143,
    facts_extracted: 7342,
    facts_today: 210,
    needs_review: 23,
    unmatched_entities: 12,
    high_confidence_pct: 91.4
  },
  entities_by_type: [
    { name: "Organization", count: 740, color: "#3b82f6" },
    { name: "Product", count: 580, color: "#10b981" },
    { name: "Contract", count: 310, color: "#f59e0b" },
    { name: "Person", count: 290, color: "#8b5cf6" },
    { name: "Invoice", count: 220, color: "#06b6d4" },
    { name: "Money", count: 180, color: "#14b8a6" },
    { name: "Date", count: 161, color: "#64748b" }
  ],
  extraction_activity_timeline: [
    { date: "Mar 23", documents: 14, facts: 110, entities: 85 },
    { date: "Mar 24", documents: 19, facts: 145, entities: 112 },
    { date: "Mar 25", documents: 23, facts: 190, entities: 138 },
    { date: "Mar 26", documents: 18, facts: 160, entities: 105 },
    { date: "Mar 27", documents: 26, facts: 235, entities: 164 },
    { date: "Mar 28", documents: 31, facts: 280, entities: 195 },
    { date: "Mar 29", documents: 38, facts: 340, entities: 248 }
  ],
  confidence_distribution: [
    { range: "90-100% (High)", count: 1890, color: "#10b981" },
    { range: "80-89% (Medium)", count: 420, color: "#3b82f6" },
    { range: "70-79% (Low)", count: 132, color: "#f59e0b" },
    { range: "< 70% (Flagged)", count: 39, color: "#ef4444" }
  ],
  review_status_breakdown: [
    { name: "Auto-Verified", count: 2240, color: "#10b981" },
    { name: "Human-Approved", count: 185, color: "#3b82f6" },
    { name: "Pending Review", count: 23, color: "#f59e0b" },
    { name: "Rejected Hallucinations", count: 33, color: "#ef4444" }
  ]
};
